/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Table.java
 *
 * Created on Oct 23, 2012, 1:41:32 PM
 */
package agile;
import java.util.*;
import java.io.*;
import javax.swing.*;
import sun.audio.*;


/**
 *
 * @author admin
 */
public class Table extends javax.swing.JFrame {
    public String[] a = new String[36];
    public int[] status = new int[4];
    public int playerTurn = 0;
    public int selectvalue;
    Random generator = new Random();
    Icon icon = new ImageIcon("bome_internet_resize.jpg");
    Icon icon1 = new ImageIcon("07_resize.jpg");
    Icon icon2 = new ImageIcon("1_resize.png");
    Icon icon3 = new ImageIcon("2_resize.jpg");
    /** Creates new form Table */
    static AudioStream as;
    static AudioStream as1;
    public static void IDatabase() {
       try {
          InputStream in = new FileInputStream("bomb.wav");
          as = new AudioStream(in);
          AudioPlayer.player.start(as);
          AudioPlayer.player.stop(as1);
       } catch (IOException e) {

       }
    }
    public static void IDatabase1() {
        try {
           InputStream in = new FileInputStream("sound.wav");
           as1 = new AudioStream(in);
           AudioPlayer.player.start(as1);
        } catch (IOException e) {

        }
     }
    public void genbomb(){
         List<Integer> generatedNumbers = new ArrayList<Integer>();
        for(int i=0; i<36; i++) { //generate 10 numbers
                generatedNumbers.add(i);
        }
        Collections.shuffle(generatedNumbers);

        for(int j = 0 ; j<36 ; j++){
        	a[j] = "X";
        }
        List<Integer> selectedNumbers = new ArrayList<Integer>();
        for(int j=0; j<6; j++) { //select only 5 number
                selectedNumbers.add(generatedNumbers.get(j));
                selectvalue = selectedNumbers.get(j);  
                a[selectvalue] = "O";
        }

    }
    public Table() {
        initComponents();
        genbomb();
        jButton6.setIcon(icon3);
        IDatabase1();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        label1.setText("Player Turn");

        jButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton6StateChanged(evt);
            }
        });

        jButton5.setText("reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 255, 255));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(153, 255, 255));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(153, 255, 255));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(153, 255, 255));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton28.setBackground(new java.awt.Color(153, 255, 255));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(153, 255, 255));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(153, 255, 255));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(153, 255, 255));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(153, 255, 255));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(153, 255, 255));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(153, 255, 255));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 255, 255));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(153, 255, 255));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(153, 255, 255));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(153, 255, 255));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(153, 255, 255));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(153, 255, 255));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(153, 255, 255));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton38.setBackground(new java.awt.Color(153, 255, 255));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton37.setBackground(new java.awt.Color(153, 255, 255));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(153, 255, 255));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(153, 255, 255));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setBackground(new java.awt.Color(153, 255, 255));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setBackground(new java.awt.Color(153, 255, 255));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(153, 255, 255));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(153, 255, 255));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(153, 255, 255));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 255, 255));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton5))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Icon carIcon = new ImageIcon("10584701-you-lose.jpg");
private void check(String b){
	if(b == "O"){
		JOptionPane.showMessageDialog(null, null, "You....Lose",0, carIcon);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jButton11.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
        jButton17.setEnabled(false);
        jButton18.setEnabled(false);
        jButton19.setEnabled(false);
        jButton20.setEnabled(false);
        jButton21.setEnabled(false);
        jButton22.setEnabled(false);
        jButton23.setEnabled(false);
        jButton24.setEnabled(false);
        jButton25.setEnabled(false);
        jButton26.setEnabled(false);
        jButton27.setEnabled(false);
        jButton28.setEnabled(false);
        jButton29.setEnabled(false);
        jButton30.setEnabled(false);
        jButton31.setEnabled(false);
        jButton32.setEnabled(false);
        jButton33.setEnabled(false);
        jButton34.setEnabled(false);
        jButton35.setEnabled(false);
        jButton36.setEnabled(false);
        jButton37.setEnabled(false);
        jButton38.setEnabled(false);
	}
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    jButton1.setBackground(new java.awt.Color(255, 255, 255));
    if(a[0]=="O"){
		jButton1.setIcon(icon);
		IDatabase();
	}
    else if(a[0] == "X"){
    	jButton1.setIcon(icon1);
    }
    if(playerTurn==0) {
        playerTurn = 1;
        jButton6.setIcon(icon2);
    }
    else if(playerTurn==1) {
        playerTurn = 0;
        jButton6.setIcon(icon3);
    }
    check(a[0]);
    jButton1.setEnabled(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    jButton2.setBackground(new java.awt.Color(255, 0, 255));
    if(a[1]=="O"){
		jButton2.setIcon(icon);
		IDatabase();
	}
    else if(a[1] == "X"){
    	jButton2.setIcon(icon1);
    }
    
    if(playerTurn==0) {
        playerTurn = 1;
        jButton6.setIcon(icon2);
    }
    else if(playerTurn==1) {
        playerTurn = 0;
        jButton6.setIcon(icon3);
    }
    check(a[1]);
    jButton2.setEnabled(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    jButton3.setBackground(new java.awt.Color(255, 0, 255));
    if(a[2]=="O"){
		jButton3.setIcon(icon);
		IDatabase();
	}
    else if(a[2] == "X"){
    	jButton3.setIcon(icon1);
    }
    
    if(playerTurn==0) {
        playerTurn = 1;
        jButton6.setIcon(icon2);
    }
    else if(playerTurn==1) {
        playerTurn = 0;
        jButton6.setIcon(icon3);
    }
    check(a[2]);
    jButton3.setEnabled(false);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    jButton4.setBackground(new java.awt.Color(255, 0, 255));
    if(a[3]=="O"){
		jButton4.setIcon(icon);
		IDatabase();
	}
    else if(a[3] == "X"){
    	jButton4.setIcon(icon1);
    }
    
    if(playerTurn==0) {
        playerTurn = 1;
        jButton6.setIcon(icon2);
    }
    else if(playerTurn==1) {
        playerTurn = 0;
        jButton6.setIcon(icon3);
    }
    check(a[3]);
    jButton4.setEnabled(false);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("");
        jButton1.setIcon(null);
        jButton2.setIcon(null);
        jButton3.setIcon(null);
        jButton4.setIcon(null);
        jButton7.setIcon(null);
        jButton8.setIcon(null);
        jButton9.setIcon(null);
        jButton10.setIcon(null);
        jButton11.setIcon(null);
        jButton12.setIcon(null);
        jButton13.setIcon(null);
        jButton14.setIcon(null);
        jButton15.setIcon(null);
        jButton16.setIcon(null);
        jButton17.setIcon(null);
        jButton18.setIcon(null);
        jButton19.setIcon(null);
        jButton20.setIcon(null);
        jButton21.setIcon(null);
        jButton22.setIcon(null);
        jButton23.setIcon(null);
        jButton24.setIcon(null);
        jButton25.setIcon(null);
        jButton26.setIcon(null);
        jButton27.setIcon(null);
        jButton28.setIcon(null);
        jButton29.setIcon(null);
        jButton30.setIcon(null);
        jButton31.setIcon(null);
        jButton32.setIcon(null);
        jButton33.setIcon(null);
        jButton34.setIcon(null);
        jButton35.setIcon(null);
        jButton36.setIcon(null);
        jButton37.setIcon(null);
        jButton38.setIcon(null);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
        jButton17.setEnabled(true);
        jButton18.setEnabled(true);
        jButton19.setEnabled(true);
        jButton20.setEnabled(true);
        jButton21.setEnabled(true);
        jButton22.setEnabled(true);
        jButton23.setEnabled(true);
        jButton24.setEnabled(true);
        jButton25.setEnabled(true);
        jButton26.setEnabled(true);
        jButton27.setEnabled(true);
        jButton28.setEnabled(true);
        jButton29.setEnabled(true);
        jButton30.setEnabled(true);
        jButton31.setEnabled(true);
        jButton32.setEnabled(true);
        jButton33.setEnabled(true);
        jButton34.setEnabled(true);
        jButton35.setEnabled(true);
        jButton36.setEnabled(true);
        jButton37.setEnabled(true);
        jButton38.setEnabled(true);
        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setText("");
        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setText("");
        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setText("");

                jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setText("");
                jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.setText("");
                jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.setText("");
                jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setText("");
                jButton11.setBackground(new java.awt.Color(153, 255, 255));
        jButton11.setText("");
                jButton12.setBackground(new java.awt.Color(153, 255, 255));
        jButton12.setText("");
                jButton13.setBackground(new java.awt.Color(153, 255, 255));
        jButton13.setText("");
                jButton14.setBackground(new java.awt.Color(153, 255, 255));
        jButton14.setText("");
                jButton15.setBackground(new java.awt.Color(153, 255, 255));
        jButton15.setText("");
                jButton16.setBackground(new java.awt.Color(153, 255, 255));
        jButton16.setText("");
                jButton17.setBackground(new java.awt.Color(153, 255, 255));
        jButton17.setText("");
                jButton18.setBackground(new java.awt.Color(153, 255, 255));
        jButton18.setText("");
        jButton19.setBackground(new java.awt.Color(153, 255, 255));
        jButton19.setText("");
                jButton20.setBackground(new java.awt.Color(153, 255, 255));
        jButton20.setText("");
                jButton21.setBackground(new java.awt.Color(153, 255, 255));
        jButton21.setText("");
                jButton22.setBackground(new java.awt.Color(153, 255, 255));
        jButton22.setText("");
                jButton23.setBackground(new java.awt.Color(153, 255, 255));
        jButton23.setText("");
                jButton24.setBackground(new java.awt.Color(153, 255, 255));
        jButton24.setText("");
                jButton25.setBackground(new java.awt.Color(153, 255, 255));
        jButton25.setText("");
                jButton26.setBackground(new java.awt.Color(153, 255, 255));
        jButton26.setText("");
                jButton27.setBackground(new java.awt.Color(153, 255, 255));
        jButton27.setText("");
                jButton28.setBackground(new java.awt.Color(153, 255, 255));
        jButton28.setText("");
                jButton29.setBackground(new java.awt.Color(153, 255, 255));
        jButton29.setText("");
                jButton30.setBackground(new java.awt.Color(153, 255, 255));
        jButton30.setText("");
                jButton31.setBackground(new java.awt.Color(153, 255, 255));
        jButton31.setText("");
                jButton32.setBackground(new java.awt.Color(153, 255, 255));
        jButton32.setText("");
                jButton33.setBackground(new java.awt.Color(153, 255, 255));
        jButton33.setText("");
                jButton34.setBackground(new java.awt.Color(153, 255, 255));
        jButton34.setText("");
                jButton35.setBackground(new java.awt.Color(153, 255, 255));
        jButton35.setText("");
                jButton36.setBackground(new java.awt.Color(153, 255, 255));
        jButton36.setText("");
                jButton37.setBackground(new java.awt.Color(153, 255, 255));
        jButton37.setText("");
                jButton38.setBackground(new java.awt.Color(153, 255, 255));
        jButton38.setText("");
        
        playerTurn=0;
        jButton6.setIcon(icon3);
        genbomb();
		AudioPlayer.player.stop(as1);
        IDatabase1();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton6StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6StateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setBackground(new java.awt.Color(255, 0, 255));
        if(a[4]=="O"){
    		jButton7.setIcon(icon);
    		IDatabase();
    	}
        else if(a[4] == "X"){
        	jButton7.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[4]);
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setBackground(new java.awt.Color(255, 0, 255));
        if(a[5]=="O"){
    		jButton8.setIcon(icon);
    		IDatabase();
    	}
        else if(a[5] == "X"){
        	jButton8.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[5]);
        jButton8.setEnabled(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jButton9.setBackground(new java.awt.Color(255, 0, 255));
        if(a[6]=="O"){
    		jButton9.setIcon(icon);
    		IDatabase();
    	}
        else if(a[6] == "X"){
        	jButton9.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[6]);
        jButton9.setEnabled(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jButton10.setBackground(new java.awt.Color(255, 0, 255));
        if(a[7]=="O"){
    		jButton10.setIcon(icon);
    		IDatabase();
    	}
        else if(a[7] == "X"){
        	jButton10.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        
        check(a[7]);
        jButton10.setEnabled(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jButton11.setBackground(new java.awt.Color(255, 0, 255));
        if(a[8]=="O"){
    		jButton11.setIcon(icon);
    		IDatabase();
    	}
        else if(a[8] == "X"){
        	jButton11.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[8]);
        jButton11.setEnabled(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jButton12.setBackground(new java.awt.Color(255, 0, 255));
        if(a[9]=="O"){
    		jButton12.setIcon(icon);
    		IDatabase();
    	}
        else if(a[9] == "X"){
        	jButton12.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[9]);
        jButton12.setEnabled(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jButton13.setBackground(new java.awt.Color(255, 0, 255));
        if(a[10]=="O"){
    		jButton13.setIcon(icon);
    		IDatabase();
    	}
        else if(a[10] == "X"){
        	jButton13.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[10]);
        jButton13.setEnabled(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jButton14.setBackground(new java.awt.Color(255, 0, 255));
        if(a[11]=="O"){
    		jButton14.setIcon(icon);
    		IDatabase();
    	}
        else if(a[11] == "X"){
        	jButton14.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[11]);
        jButton14.setEnabled(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jButton15.setBackground(new java.awt.Color(255, 0, 255));
        if(a[12]=="O"){
    		jButton15.setIcon(icon);
    		IDatabase();
    	}
        else if(a[12] == "X"){
        	jButton15.setIcon(icon1);
        }
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[12]);
        jButton15.setEnabled(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jButton16.setBackground(new java.awt.Color(255, 0, 255));
        if(a[13]=="O"){
    		jButton16.setIcon(icon);
    		IDatabase();
    	}
        else if(a[13] == "X"){
        	jButton16.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[13]);
        jButton16.setEnabled(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jButton17.setBackground(new java.awt.Color(255, 0, 255));
        if(a[14]=="O"){
    		jButton17.setIcon(icon);
    		IDatabase();
    	}
        else if(a[14] == "X"){
        	jButton17.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[14]);
        jButton17.setEnabled(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jButton18.setBackground(new java.awt.Color(255, 0, 255));
        if(a[15]=="O"){
    		jButton18.setIcon(icon);
    		IDatabase();
    	}
        else if(a[15] == "X"){
        	jButton18.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[15]);
        jButton18.setEnabled(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jButton19.setBackground(new java.awt.Color(255, 0, 255));
        if(a[16]=="O"){
    		jButton19.setIcon(icon);
    		IDatabase();
    	}
        else if(a[16] == "X"){
        	jButton19.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[16]);
        jButton19.setEnabled(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
                jButton20.setBackground(new java.awt.Color(255, 0, 255));
                if(a[17]=="O"){
            		jButton20.setIcon(icon);
            		IDatabase();
            	}
                else if(a[17] == "X"){
                	jButton20.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[17]);
        jButton20.setEnabled(false);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
                jButton21.setBackground(new java.awt.Color(255, 0, 255));
                if(a[18]=="O"){
            		jButton21.setIcon(icon);
            		IDatabase();
            	}
                else if(a[18] == "X"){
                	jButton21.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[18]);
        jButton21.setEnabled(false);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
                jButton22.setBackground(new java.awt.Color(255, 0, 255));
                if(a[19]=="O"){
            		jButton22.setIcon(icon);
            		IDatabase();
            	}
                else if(a[19] == "X"){
                	jButton22.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[19]);
        jButton22.setEnabled(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
                jButton23.setBackground(new java.awt.Color(255, 0, 255));
                if(a[20]=="O"){
            		jButton23.setIcon(icon);
            		IDatabase();
            	}
                else if(a[20] == "X"){
                	jButton23.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[20]);
        jButton23.setEnabled(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
                jButton24.setBackground(new java.awt.Color(255, 0, 255));
                if(a[21]=="O"){
            		jButton24.setIcon(icon);
            		IDatabase();
            	}
                else if(a[21] == "X"){
                	jButton24.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[21]);
        jButton24.setEnabled(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
                jButton25.setBackground(new java.awt.Color(255, 0, 255));
                if(a[22]=="O"){
            		jButton25.setIcon(icon);
            		IDatabase();
            	}
                else if(a[22] == "X"){
                	jButton25.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[22]);
        jButton25.setEnabled(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
                jButton26.setBackground(new java.awt.Color(255, 0, 255));
                if(a[23]=="O"){
            		jButton26.setIcon(icon);
            		IDatabase();
            	}
                else if(a[23] == "X"){
                	jButton26.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[23]);
        jButton26.setEnabled(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
                jButton27.setBackground(new java.awt.Color(255, 0, 255));
                if(a[24]=="O"){
            		jButton27.setIcon(icon);
            		IDatabase();
            	}
                else if(a[24] == "X"){
                	jButton27.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[24]);
        jButton27.setEnabled(false);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
                jButton28.setBackground(new java.awt.Color(255, 0, 255));
                if(a[25]=="O"){
            		jButton28.setIcon(icon);
            		IDatabase();
            	}
                else if(a[25] == "X"){
                	jButton28.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[25]);
        jButton28.setEnabled(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
                jButton29.setBackground(new java.awt.Color(255, 0, 255));
                if(a[26]=="O"){
            		jButton29.setIcon(icon);
            		IDatabase();
            	}
                else if(a[26] == "X"){
                	jButton29.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[26]);
        jButton29.setEnabled(false);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
                jButton30.setBackground(new java.awt.Color(255, 0, 255));
                if(a[27]=="O"){
            		jButton30.setIcon(icon);
            		IDatabase();
            	}
                else if(a[27] == "X"){
                	jButton30.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[27]);
        jButton30.setEnabled(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
                jButton31.setBackground(new java.awt.Color(255, 0, 255));
                if(a[28]=="O"){
            		jButton31.setIcon(icon);
            		IDatabase();
            	}
                else if(a[28] == "X"){
                	jButton31.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[28]);
        jButton31.setEnabled(false);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
                jButton32.setBackground(new java.awt.Color(255, 0, 255));
                if(a[29]=="O"){
            		jButton32.setIcon(icon);
            		IDatabase();
            	}
                else if(a[29] == "X"){
                	jButton32.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[29]);
        jButton32.setEnabled(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
                jButton33.setBackground(new java.awt.Color(255, 0, 255));
                if(a[30]=="O"){
            		jButton33.setIcon(icon);
            		IDatabase();
            	}
                else if(a[30] == "X"){
                	jButton33.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[30]);
        jButton33.setEnabled(false);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
                jButton34.setBackground(new java.awt.Color(255, 0, 255));
                if(a[31]=="O"){
            		jButton34.setIcon(icon);
            		IDatabase();
            	}
                else if(a[31] == "X"){
                	jButton34.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[31]);
        jButton34.setEnabled(false);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
                jButton35.setBackground(new java.awt.Color(255, 0, 255));
                if(a[32]=="O"){
            		jButton35.setIcon(icon);
            		IDatabase();
            	}
                else if(a[32] == "X"){
                	jButton35.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[32]);
        jButton35.setEnabled(false);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
                jButton36.setBackground(new java.awt.Color(255, 0, 255));
                if(a[33]=="O"){
            		jButton36.setIcon(icon);
            		IDatabase();
            	}
                else if(a[33] == "X"){
                	jButton36.setIcon(icon1);
                }
       
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[33]);
        jButton36.setEnabled(false);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
                jButton37.setBackground(new java.awt.Color(255, 0, 255));
                if(a[34]=="O"){
            		jButton37.setIcon(icon);
            		IDatabase();
            	}
                else if(a[34] == "X"){
                	jButton37.setIcon(icon1);
                }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[34]);
        jButton37.setEnabled(false);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        jButton38.setBackground(new java.awt.Color(255, 0, 255));
        if(a[35]=="O"){
    		jButton38.setIcon(icon);
    		IDatabase();
    	}
        else if(a[35] == "X"){
        	jButton38.setIcon(icon1);
        }
        
        if(playerTurn==0) {
            playerTurn = 1;
            jButton6.setIcon(icon2);
        }
        else if(playerTurn==1) {
            playerTurn = 0;
            jButton6.setIcon(icon3);
        }
        check(a[35]);
        jButton38.setEnabled(false);
    }//GEN-LAST:event_jButton38ActionPerformed

    /**
     * @param args the command line arguments
     * @return 
     * @throws IOException 
     * @throws UnsupportedAudioFileException 
     * @throws LineUnavailableException 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run(){
                new Table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
